trainer:
  devices: 1
  num_nodes: 1
  max_epochs: 10
  max_steps: -1
  accumulate_grad_batches: 1
  gradient_clip_val: 0.0
  precision: 16
  accelerator: gpu
  log_every_n_steps: 1
  val_check_interval: 1.0
  resume_from_checkpoint: null
  num_sanity_val_steps: 0
  enable_checkpointing: false
  logger: false
  strategy: null
model:
  nemo_path: text_classification_model.nemo
  tokenizer:
    tokenizer_name: ${model.language_model.pretrained_model_name}
    vocab_file: null
    tokenizer_model: null
    special_tokens: null
  language_model:
    pretrained_model_name: airesearch/wangchanberta-base-att-spm-uncased
    lm_checkpoint: null
    config_file: null
    config: null
  classifier_head:
    num_output_layers: 1
    fc_dropout: 0.2
  class_labels:
    class_labels_file: null
  dataset:
    num_classes: 3
    do_lower_case: false
    max_seq_length: 510
    class_balancing: null
    use_cache: false
  train_ds:
    file_path: /content/drive/MyDrive/NLP_Workshop/NLP_Workshop_Content/data/train_nemo.tsv
    batch_size: 16
    shuffle: true
    num_samples: -1
    num_workers: 3
    drop_last: false
    pin_memory: true
  validation_ds:
    file_path: /content/drive/MyDrive/NLP_Workshop/NLP_Workshop_Content/data/val_nemo.tsv
    batch_size: 16
    shuffle: false
    num_samples: -1
    num_workers: 1
    drop_last: false
    pin_memory: true
  test_ds:
    file_path: /content/drive/MyDrive/NLP_Workshop/NLP_Workshop_Content/data/test_nemo.tsv
    batch_size: 16
    shuffle: false
    num_samples: -1
    num_workers: 1
    drop_last: false
    pin_memory: true
  optim:
    name: adam
    lr: 1.0e-05
    betas:
    - 0.9
    - 0.999
    weight_decay: 0.01
    sched:
      name: ReduceLROnPlateau
      mode: min
      monitor: val_loss
      factor: 0.1
      patience: 3
      min_lr: 1.0e-07
  infer_samples:
  - by the end of no such thing the audience , like beatrice , has a watchful affection
    for the monster .
  - director rob marshall went out gunning to make a great one .
  - uneasy mishmash of styles and genres .
exp_manager:
  exp_dir: /content/drive/MyDrive/NLP_Workshop/NLP_Workshop_Content/checkpoint
  name: TextClassification
  create_tensorboard_logger: true
  create_checkpoint_callback: true
save_to: /content/drive/MyDrive/NLP_Workshop/NLP_Workshop_Content/nemo_model/model.nemo
export_to: /content/drive/MyDrive/NLP_Workshop/NLP_Workshop_Content/nemo_model/model.onnx
